#ifndef WAVESNAP_GESTURE_DETECTOR_H
#define WAVESNAP_GESTURE_DETECTOR_H

#include <stddef.h>
#include <stdint.h>

enum GestureResult { GESTURE_RESULT_NONE = 0, GESTURE_RESULT_MOTION = 1, GESTURE_RESULT_WAVE = 2 };

enum GestureError {
    GESTURE_ERROR_NOT_INITIALIZED = -1,
    GESTURE_ERROR_INVALID_ARGUMENT = -2,
    GESTURE_ERROR_JPEG_DECODE = -3,
    GESTURE_ERROR_JPEG_DIMENSIONS = -4
};

enum GestureFlags {
    GESTURE_FLAG_GLOBAL_MOTION = 1,
    GESTURE_FLAG_EXPOSURE_CHANGE = 2,
    GESTURE_FLAG_COMPONENT_TOO_LARGE = 4,
    GESTURE_FLAG_NO_PLAUSIBLE_COMPONENT = 8,
    GESTURE_FLAG_TRAJECTORY_REJECTED = 16,
    GESTURE_FLAG_CAMERA_TRANSLATION = 32,
    GESTURE_FLAG_LOCAL_FLOW = 64
};

#endif
